=begin
#Data API

#Serves the Clever Data API

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'

# Unit tests for CleverApi::DistrictAdminsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DistrictAdminsApi' do
  before do
    # run before each test
    @instance = CleverApi::DistrictAdminsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DistrictAdminsApi' do
    it 'should create an instance of DistrictAdminsApi' do
      expect(@instance).to be_instance_of(CleverApi::DistrictAdminsApi)
    end
  end

  # unit tests for get_district_admin
  # Returns a specific district admin
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DistrictAdminResponse]
  describe 'get_district_admin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_admins
  # Returns a list of district admins
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit 
  # @option opts [String] :starting_after 
  # @option opts [String] :ending_before 
  # @option opts [String] :count 
  # @return [DistrictAdminsResponse]
  describe 'get_district_admins test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_district_for_district_admin
  # Returns the district for a district admin
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DistrictResponse]
  describe 'get_district_for_district_admin test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
