=begin
#Clever API

#The Clever API

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CleverApi::TeacherObject
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TeacherObject' do
  before do
    # run before each test
    @instance = CleverApi::TeacherObject.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TeacherObject' do
    it 'should create an instance of TeacherObject' do
      expect(@instance).to be_instance_of(CleverApi::TeacherObject)
    end
  end
  describe 'test attribute "object"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
