=begin
#Data API

#Serves the Clever Data API

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::TermResponse
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TermResponse' do
  before do
    # run before each test
    @instance = SwaggerClient::TermResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TermResponse' do
    it 'should create an instance of TermResponse' do
      expect(@instance).to be_instance_of(SwaggerClient::TermResponse)
    end
  end
  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
