=begin
#Clever API

#The Clever API

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

# Common files
require 'clever_api/api_client'
require 'clever_api/api_error'
require 'clever_api/version'
require 'clever_api/configuration'

# Models
require 'clever_api/models/admin_name'
require 'clever_api/models/bad_request'
require 'clever_api/models/contact'
require 'clever_api/models/contact_object'
require 'clever_api/models/contact_response'
require 'clever_api/models/contacts_created'
require 'clever_api/models/contacts_deleted'
require 'clever_api/models/contacts_response'
require 'clever_api/models/contacts_updated'
require 'clever_api/models/course'
require 'clever_api/models/course_object'
require 'clever_api/models/course_response'
require 'clever_api/models/courses_created'
require 'clever_api/models/courses_deleted'
require 'clever_api/models/courses_response'
require 'clever_api/models/courses_updated'
require 'clever_api/models/credentials'
require 'clever_api/models/district'
require 'clever_api/models/district_admin'
require 'clever_api/models/district_admin_object'
require 'clever_api/models/district_admin_response'
require 'clever_api/models/district_admins_response'
require 'clever_api/models/district_object'
require 'clever_api/models/district_response'
require 'clever_api/models/districtadmins_created'
require 'clever_api/models/districtadmins_deleted'
require 'clever_api/models/districtadmins_updated'
require 'clever_api/models/districts_created'
require 'clever_api/models/districts_deleted'
require 'clever_api/models/districts_response'
require 'clever_api/models/districts_updated'
require 'clever_api/models/event'
require 'clever_api/models/event_response'
require 'clever_api/models/events_response'
require 'clever_api/models/internal_error'
require 'clever_api/models/link'
require 'clever_api/models/location'
require 'clever_api/models/name'
require 'clever_api/models/not_found'
require 'clever_api/models/principal'
require 'clever_api/models/school'
require 'clever_api/models/school_admin'
require 'clever_api/models/school_admin_object'
require 'clever_api/models/school_admin_response'
require 'clever_api/models/school_admins_response'
require 'clever_api/models/school_enrollment'
require 'clever_api/models/school_object'
require 'clever_api/models/school_response'
require 'clever_api/models/schooladmins_created'
require 'clever_api/models/schooladmins_deleted'
require 'clever_api/models/schooladmins_updated'
require 'clever_api/models/schools_created'
require 'clever_api/models/schools_deleted'
require 'clever_api/models/schools_response'
require 'clever_api/models/schools_updated'
require 'clever_api/models/section'
require 'clever_api/models/section_object'
require 'clever_api/models/section_response'
require 'clever_api/models/sections_created'
require 'clever_api/models/sections_deleted'
require 'clever_api/models/sections_response'
require 'clever_api/models/sections_updated'
require 'clever_api/models/student'
require 'clever_api/models/student_object'
require 'clever_api/models/student_response'
require 'clever_api/models/students_created'
require 'clever_api/models/students_deleted'
require 'clever_api/models/students_response'
require 'clever_api/models/students_updated'
require 'clever_api/models/teacher'
require 'clever_api/models/teacher_object'
require 'clever_api/models/teacher_response'
require 'clever_api/models/teachers_created'
require 'clever_api/models/teachers_deleted'
require 'clever_api/models/teachers_response'
require 'clever_api/models/teachers_updated'
require 'clever_api/models/term'
require 'clever_api/models/term_object'
require 'clever_api/models/term_response'
require 'clever_api/models/terms_created'
require 'clever_api/models/terms_deleted'
require 'clever_api/models/terms_response'
require 'clever_api/models/terms_updated'

# APIs
require 'clever_api/api/data_api'
require 'clever_api/api/events_api'

module CleverApi
  class << self
    # Customize default settings for the SDK using block.
    #   CleverApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
