=begin
#Data API

#Serves the Clever Data API

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.24
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/admin_name'
require 'swagger_client/models/bad_request'
require 'swagger_client/models/contact'
require 'swagger_client/models/contact_response'
require 'swagger_client/models/contacts_response'
require 'swagger_client/models/course'
require 'swagger_client/models/course_response'
require 'swagger_client/models/courses_response'
require 'swagger_client/models/credentials'
require 'swagger_client/models/district'
require 'swagger_client/models/district_admin'
require 'swagger_client/models/district_admin_response'
require 'swagger_client/models/district_admins_response'
require 'swagger_client/models/district_response'
require 'swagger_client/models/districts_response'
require 'swagger_client/models/internal_error'
require 'swagger_client/models/link'
require 'swagger_client/models/location'
require 'swagger_client/models/name'
require 'swagger_client/models/not_found'
require 'swagger_client/models/principal'
require 'swagger_client/models/school'
require 'swagger_client/models/school_admin'
require 'swagger_client/models/school_admin_response'
require 'swagger_client/models/school_admins_response'
require 'swagger_client/models/school_enrollment'
require 'swagger_client/models/school_response'
require 'swagger_client/models/schools_response'
require 'swagger_client/models/section'
require 'swagger_client/models/section_response'
require 'swagger_client/models/sections_response'
require 'swagger_client/models/student'
require 'swagger_client/models/student_response'
require 'swagger_client/models/students_response'
require 'swagger_client/models/teacher'
require 'swagger_client/models/teacher_response'
require 'swagger_client/models/teachers_response'
require 'swagger_client/models/term'
require 'swagger_client/models/term_response'
require 'swagger_client/models/terms_response'

# APIs
require 'swagger_client/api/contacts_api'
require 'swagger_client/api/courses_api'
require 'swagger_client/api/district_admins_api'
require 'swagger_client/api/districts_api'
require 'swagger_client/api/school_admins_api'
require 'swagger_client/api/schools_api'
require 'swagger_client/api/sections_api'
require 'swagger_client/api/students_api'
require 'swagger_client/api/teachers_api'
require 'swagger_client/api/terms_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
